import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, radius, shadow, spacing } from '@/constants/theme';
import { Product } from '@/types';
import { formatMAD } from '@/utils/format';
export function Logo(){return <View style={s.logo}><View style={s.mark}><Text style={s.markText}>PZ</Text></View><View><Text style={s.logoText}>Pharmacie Ziraoui</Text><Text style={s.logoSub}>Parapharmacie premium</Text></View></View>}
export function Card({children,style}:{children:React.ReactNode;style?:object}){return <View style={[s.card,style]}>{children}</View>}
export function Button({title,onPress,variant='primary',icon}:{title:string;onPress?:()=>void;variant?:'primary'|'outline'|'gold';icon?:keyof typeof Ionicons.glyphMap}){return <Pressable onPress={onPress} style={[s.btn,variant==='outline'&&s.outline,variant==='gold'&&s.gold]}>{icon&&<Ionicons name={icon} size={18} color={variant==='outline'?colors.deepGreen:colors.white}/>}<Text style={[s.btnText,variant==='outline'&&{color:colors.deepGreen}]}>{title}</Text></Pressable>}
export function SearchBox({value,onChangeText,placeholder='Rechercher un produit, une marque...'}:{value:string;onChangeText:(v:string)=>void;placeholder?:string}){return <View style={s.search}><Ionicons name="search" size={20} color={colors.muted}/><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} style={s.input} /></View>}
export function ProductCard({product,onPress,onAdd}:{product:Product;onPress?:()=>void;onAdd?:()=>void}){return <Pressable onPress={onPress} style={s.product}><Image source={{uri:product.image}} style={s.image}/>{product.isPromo&&<Text style={s.badge}>Promo</Text>}<Text style={s.brand}>{product.brand}</Text><Text numberOfLines={2} style={s.name}>{product.name}</Text><Text style={s.price}>{formatMAD(product.price)}</Text>{product.oldPrice&&<Text style={s.old}>{formatMAD(product.oldPrice)}</Text>}<Button title="Ajouter" onPress={onAdd} /> </Pressable>}
export const s=StyleSheet.create({logo:{flexDirection:'row',alignItems:'center',gap:10},mark:{width:48,height:48,borderRadius:16,backgroundColor:colors.deepGreen,alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:colors.gold},markText:{color:colors.white,fontWeight:'800'},logoText:{fontSize:21,fontWeight:'800',color:colors.deepGreen},logoSub:{color:colors.muted},card:{backgroundColor:colors.white,borderRadius:radius.lg,padding:spacing.lg,...shadow},btn:{backgroundColor:colors.deepGreen,borderRadius:radius.pill,paddingVertical:12,paddingHorizontal:16,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},outline:{backgroundColor:'transparent',borderWidth:1,borderColor:colors.deepGreen},gold:{backgroundColor:colors.gold},btnText:{color:colors.white,fontWeight:'800'},search:{backgroundColor:colors.white,borderRadius:radius.pill,paddingHorizontal:16,paddingVertical:4,flexDirection:'row',alignItems:'center',gap:8,...shadow},input:{flex:1,height:44},product:{width:170,backgroundColor:colors.white,borderRadius:radius.lg,padding:12,marginRight:12,...shadow},image:{width:'100%',height:115,borderRadius:radius.md,backgroundColor:colors.lightGreen},badge:{position:'absolute',top:18,left:18,backgroundColor:colors.gold,color:colors.white,paddingHorizontal:8,paddingVertical:3,borderRadius:radius.pill,fontWeight:'800'},brand:{marginTop:8,color:colors.muted,fontSize:12},name:{fontWeight:'800',color:colors.ink,minHeight:38},price:{color:colors.deepGreen,fontWeight:'900',marginTop:6},old:{color:colors.muted,textDecorationLine:'line-through',fontSize:12}});
