import { Linking, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, Logo, ProductCard, SearchBox } from '@/components/ui';
import { appConfig } from '@/constants/config';
import { colors } from '@/constants/theme';
import { categories } from '@/data/categories';
import { products } from '@/data/products';
import { useCart } from '@/hooks/useCart';
import { Section, Screen } from './Common';
export default function HomeScreen(){const{addToCart}=useCart();return <Screen><Logo/><View style={{height:18}}/><SearchBox value="" onChangeText={()=>router.push('/search')}/><Card style={{marginTop:18,backgroundColor:colors.deepGreen}}><Text style={{color:colors.white,fontSize:26,fontWeight:'900'}}>Routine beauté & bien-être</Text><Text style={{color:colors.lightGreen,marginVertical:8}}>Promotions de démonstration, conseils en pharmacie et livraison disponible.</Text><Button title="Voir le catalogue" variant="gold" onPress={()=>router.push('/catalog')}/></Card><Section title="Catégories principales"><ScrollView horizontal showsHorizontalScrollIndicator={false}>{categories.map(c=><Card key={c.name} style={{width:150,marginRight:12}}><Text style={{fontWeight:'900',color:colors.deepGreen}}>{c.name}</Text><Text style={{color:colors.muted,marginTop:6}}>{c.description}</Text></Card>)}</ScrollView></Section><Section title="Produits populaires"><ScrollView horizontal>{products.slice(0,8).map(p=><ProductCard key={p.id} product={p} onPress={()=>router.push(`/product/${p.id}`)} onAdd={()=>addToCart(p)}/>)}</ScrollView></Section><Section title="Nouveautés"><ScrollView horizontal>{products.filter(p=>p.isNew).map(p=><ProductCard key={p.id} product={p} onPress={()=>router.push(`/product/${p.id}`)} onAdd={()=>addToCart(p)}/>)}</ScrollView></Section><Section title="Promotions"><ScrollView horizontal>{products.filter(p=>p.isPromo).slice(0,8).map(p=><ProductCard key={p.id} product={p} onPress={()=>router.push(`/product/${p.id}`)} onAdd={()=>addToCart(p)}/>)}</ScrollView></Section><Section title="Services de la pharmacie"><Card><Text>Retrait rapide · Livraison locale · Validation pharmacie pour produits sensibles · Aucun diagnostic médical dans l'application.</Text><View style={{flexDirection:'row',gap:10,marginTop:14,flexWrap:'wrap'}}><Button title="WhatsApp" icon="logo-whatsapp" onPress={()=>Linking.openURL(`https://wa.me/${appConfig.whatsapp.replace(/\D/g,'')}`)}/><Button title="Appeler" variant="outline" icon="call" onPress={()=>Linking.openURL(`tel:${appConfig.phone}`)}/></View></Card></Section><Card style={{marginTop:18,backgroundColor:colors.lightGreen}}><Text style={{fontWeight:'900',color:colors.deepGreen}}>Livraison disponible</Text><Text>Zones proches, intermédiaires et éloignées avec frais automatiques.</Text></Card></Screen>}
