import { useMemo, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Card, ProductCard, SearchBox } from '@/components/ui';
import { colors } from '@/constants/theme';
import { categories } from '@/data/categories';
import { products } from '@/data/products';
import { useCart } from '@/hooks/useCart';
import { Screen, Section } from './Common';
export default function SearchScreen(){const[q,setQ]=useState('');const[cat,setCat]=useState('');const[promo,setPromo]=useState(false);const[available,setAvailable]=useState(false);const{addToCart}=useCart();const brands=[...new Set(products.map(p=>p.brand))];const[brand,setBrand]=useState('');const filtered=useMemo(()=>products.filter(p=>(!q||`${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(q.toLowerCase()))&&(!cat||p.category===cat)&&(!brand||p.brand===brand)&&(!promo||p.isPromo)&&(!available||p.availability!=='Indisponible')&&p.price<=500),[q,cat,brand,promo,available]);const chip=(label:string,active:boolean,onPress:()=>void)=><Pressable onPress={onPress} style={{padding:10,borderRadius:99,backgroundColor:active?colors.deepGreen:colors.white,margin:4}}><Text style={{color:active?colors.white:colors.deepGreen,fontWeight:'700'}}>{label}</Text></Pressable>;return <Screen title="Recherche & filtres"><SearchBox value={q} onChangeText={setQ}/><Section title="Filtres"><Card><Text style={{fontWeight:'900'}}>Catégorie</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{chip('Toutes',!cat,()=>setCat(''))}{categories.map(c=>chip(c.name,cat===c.name,()=>setCat(c.name)))}</View><Text style={{fontWeight:'900',marginTop:8}}>Marque</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{chip('Toutes',!brand,()=>setBrand(''))}{brands.map(b=>chip(b,brand===b,()=>setBrand(b)))}</View><View style={{flexDirection:'row',flexWrap:'wrap',marginTop:8}}>{chip('Prix ≤ 500 MAD',true,()=>{})}{chip('Promotion',promo,()=>setPromo(!promo))}{chip('Disponible',available,()=>setAvailable(!available))}</View></Card></Section><Section title={`${filtered.length} résultat(s)`}><View style={{flexDirection:'row',flexWrap:'wrap',gap:14}}>{filtered.map(p=><ProductCard key={p.id} product={p} onPress={()=>router.push(`/product/${p.id}`)} onAdd={()=>addToCart(p)}/>)}</View></Section></Screen>}
